### ISSUE TITLE
Failed to spawn command elixir.  Make sure elixir is installed and in your PATH

### ISSUE THREAD

**Issue by 7sharp9** [iraasta/autocomplete-elixir#12]
But elixir is in my path:
```
Daves-MacBook-Pro:md-addins dave$ which elixir
/usr/local/bin/elixir
Daves-MacBook-Pro:md-addins dave$ elixir
Usage: elixir [options] [.exs file] [data]
```

**Comment by cloudbring** [comment]
😤 I am getting this too.

**Comment by cloudbring** [comment]
### 💻 Setup
```
$ which elixirc
/usr/local/bin/elixirc
$ brew info elixir
elixir: stable 1.0.4 (bottled), HEAD
http://elixir-lang.org/
/usr/local/Cellar/elixir/1.0.4 (329 files, 4.3M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/elixir.rb
$ elixir -v
Elixir 1.0.4
```

**Comment by ptrckbrwn** [comment]
Same here :(

**Comment by iraasta** [comment]
It's MacOS-only problem. 
You've got no acces to path from GUI. Start atom from command line and everything will work just fine. 
I've got no idea what to do about it

**Comment by iraasta** [comment]
Apparently it's for every Finder application, not only atom. 
http://apple.stackexchange.com/q/51677

**Comment by ptrckbrwn** [comment]
Lot's of plugins have a way to point to the executable in the config, you should consider doing the same.

**Comment by iraasta** [comment]
@ptrckbrwn Just did in 3df5741

**Comment by ptrckbrwn** [comment]
Awesome! :smile:

**Comment by mager** [comment]
This package was deprecated: https://atom.io/packages/autocomplete-elixir

Use `atom-elixir` instead.
