### ISSUE TITLE
elixir not found

### ISSUE THREAD

**Issue by l4u** [iraasta/autocomplete-elixir#3]
if I change  
`ac  = spawn("elixir", array.reverse())`
to
`ac  = spawn("/usr/local/bin/elixir", array.reverse())`
it works.

platform: Mac OS X 10.10.3
elixir installed with homebrew

Maybe we should find elixir in PATH?

**Comment by iraasta** [comment]
You must have "elixir" command in PATH.
I can't use strict path because of other OS users.

**Comment by l4u** [comment]
elixir is actually in $PATH
But I'm not sure why atom couldn't spawn elixir.

I've tried starting atom from the terminal but it didn't work.

**Comment by iraasta** [comment]
Is it possible that You launch atom as su, while You've got Elixir in user's $PATH
I got myself on that several times

**Comment by l4u** [comment]
Just checked with $PATH and atom without sudo but no luck.
A elixir path config should work.
Also, should we use BufferedProcess instead of spawn?

**Comment by iraasta** [comment]
I don't know what BufferedProcess is. To be honest I'm quite new to Atom environment.
What are advantages of using it over child_process?
I see it's experimental.

**Comment by l4u** [comment]
I am not sure too. I haven't written any packages for atom.
But I found that BufferedProcess is used by several packages for process spawning when I was trying to fix the elixir spawning issue.

BufferedProcess is a wrapper of ChildProcess.
- https://atom.io/docs/api/v0.192.0/BufferedProcess
- https://github.com/atom/atom/blob/v0.192.0/src/buffered-process.coffee

**Comment by noizu** [comment]
There is a similar issue on windows, switching to elixir.bat instead of elixir appears to resolve it.

**Comment by jordpo** [comment]
hm - for me the issue arises when I launch Atom using Spotlight Search or from Applications instead of the command line. Running atom in the command line spawns the elixir process correctly.

**Comment by iraasta** [comment]
I just changed `spawn` to `BufferedProcess` from Atom API. 
Please elaborate if it's any better :)

Cheers
