### ISSUE TITLE
Failed to spawn command `elixir`

### ISSUE THREAD

**Issue by fibric** [iraasta/autocomplete-elixir#7]
Getting a weird error on enabling `autocomplete-elixir`

![screenshot 2015-05-23 12 30 16](https://cloud.githubusercontent.com/assets/623932/7783590/80d56560-0147-11e5-951b-b464bef77461.png)

Elixir is installed via `brew install elixir`

```fish
> which elixir
/usr/local/bin/elixir
```

And of cause `/usr/local/bin` is in the `PATH`

```fish
> echo $PATH
/Users/fibric/.nvm/versions/io.js/v2.0.1/bin /opt/X11/bin /usr/local/MacGPG2/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin
```

```fish
> elixir -v
Elixir 1.0.4
```

What I'm doing wrong here?

Running OSX.

**Comment by iraasta** [comment]
Are You running atom from the command line or from GUI?

**Comment by iraasta** [comment]
And what version of the package are You using?

**Comment by fibric** [comment]
Started from GUI. autocomplete-elixir is in version 1.2.6 (as shown on screenshot).

**Comment by fibric** [comment]
When I am starting atom from cmd `atom .` then it works.

**Comment by fibric** [comment]
Found [this](http://apple.stackexchange.com/questions/153402/in-osx-yosemite-why-can-i-set-many-environment-variables-for-gui-apps-but-cann) and [this](http://superuser.com/questions/476752/setting-environment-variables-in-os-x-for-gui-applications). Looks like I can close this issue.
