### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by Cifer-Y** [iraasta/autocomplete-elixir#9]
Once installed autocomplete-elixir , atom will warn me with deprecation warning.

**Comment by iraasta** [comment]
I can't see any depreciation warning. Could You please make a screenshot for me or at least paste the content of the warning?

**Comment by Cifer-Y** [comment]
![deprecation cop - -users-cifer-enigma - atom atom today at 19 35 18](https://cloud.githubusercontent.com/assets/4470516/7911918/63477d3a-0895-11e5-935d-91b2faa64db9.png)

**Comment by Cifer-Y** [comment]
another question, atom report me it can not find command 'elixir' in my path, I'm sure `elixir` is in my path.
Is there any method to set path in atom? Could you tell me how, please

**Comment by iraasta** [comment]
@Cifer-Y  Yes. This is related to Mac-OS.
Every other issue is about that problem. I don't really know what to do with it.
When You start atom from GUI the path is not available for it. But when You start it from the command line it should work as intended.

**Comment by Cifer-Y** [comment]
@iraasta Thank You, command line  works well is enough ~~ :+1:

**Comment by iraasta** [comment]
@Cifer-Y You're not the only one having this issue. And I can't really test it out because I'm not using any Mac-OS machine.
But If You'll find any way to make PATH visible when starting from GUI I'd appreciate If You shared it with me, because people are nagging me about this all the time

**Comment by Cifer-Y** [comment]
@iraasta OK, I will to find
